TAIS/midpjt_0307/midpjt/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('member/', include('member.urls')),
    path('fboard/', include('fboard.urls')), 
    path('comm/', include('comm.urls')), 
    path('event/', include('event.urls')), 
    path('tai/', include('tai.urls')), 
]

TAIS/midpjt_0307/tai/urls.py
from . import views
from django.urls import path 

app_name = 'tai'

urlpatterns = [
    path('tai/', views.tai, name='tai'),
    path('tai2/', views.tai2, name='tai2'),
]

TAIS/midpjt_0307/tai/models.py
from django.db import models

# Create your models here.
class TACHART(models.Model):
    occur_yr = models.IntegerField()
    occur_mn = models.IntegerField()
    occur_hr = models.CharField(max_length=26)
    num_death = models.IntegerField()
    num_heavy_injury = models.IntegerField()
    num_middle_injury = models.IntegerField()
    num_light_injury = models.IntegerField()
    occur_city = models.CharField(max_length=26)
    occur_provin = models.CharField(max_length=26)
    occur_dong = models.CharField(max_length=26)
    occur_road_name_yn = models.CharField(max_length=26)
    road_condition = models.CharField(max_length=26)
    weath_info = models.CharField(max_length=26)
    attacker_gender = models.CharField(max_length=26)
    attacker_human_age = models.CharField(max_length=26)
    accident_gender = models.CharField(max_length=26)
    accident_human_age = models.CharField(max_length=26)

    def __str__(self) :
        return self.occur_city

TAIS/midpjt_0307/tai/views.py
import json
from django.http import JsonResponse
import cx_Oracle as ora
import pandas as pd
from django.shortcuts import render
from django.db.models import Count
from tai.models import TACHART
import pandas as pd
# Create your views here.


def tai(request):
    sub = request.GET.get('name')
    #월별
    sql2 = "select occur_mn, COUNT(*) from TAI_TACHART where OCCUR_PROVIN = '{}' group by occur_mn order by occur_mn".format(sub)
    # .format(sub)
    print('sql2 :',sql2)
    conn = connections()
    cs = conn.cursor()
    cs.execute(sql2)
    rows = cs.fetchall()
    print('rs :', rows)
    context = {'result':rows}
    with open('static/data2.json', 'w') as f : 
        json.dump(rows, f, indent=4)
    
    #지역별
    sql1 = "select OCCUR_PROVIN,count(OCCUR_PROVIN) from TAI_TACHART group by OCCUR_PROVIN"
    print('sql1 :',sql1)
    conn = connections()
    cs = conn.cursor()
    cs.execute(sql1)
    rows = cs.fetchall()

    with open('static/data1.json', 'w') as f : 
        json.dump(rows, f, indent=4)
    
    #시간별
    sql3 = "select occur_hr, COUNT(*) from TAI_TACHART where OCCUR_PROVIN = '{}' group by occur_hr order by occur_hr".format(sub)
    # .format(sub)
    print('sql3 :',sql3)
    conn = connections()
    cs = conn.cursor()
    cs.execute(sql3)
    rows = cs.fetchall()

    with open('static/data3.json', 'w') as f : 
        json.dump(rows, f, indent=4)
    
    #연령별  
    sql4 = "select * from(select ATTACKER_HUMAN_AGE, count(*) from TAI_TACHART where OCCUR_PROVIN = '{}' group by ATTACKER_HUMAN_AGE order by count(*)desc) where rownum <= 5".format(sub)
    # .format(sub)
    print('sql4 :',sql4)
    conn = connections()
    cs = conn.cursor()
    cs.execute(sql4)
    rows = cs.fetchall()

    with open('static/data4.json', 'w') as f : 
        json.dump(rows, f, indent=4)



    
    return render(request, 'tai/tai.html')

def tai2(request):
    
    sql = "select occur_mn, COUNT(*) from TAI_TACHART where OCCUR_PROVIN = '강남구' group by occur_mn order by occur_mn"
    print('sql :',sql)
    conn = connections()
    cs = conn.cursor()
    cs.execute(sql)
    rows = cs.fetchall()
    print('rs :', rows)
    
    context = {'result':rows}
    with open('static/data2.json', 'w') as f : 
        json.dump(rows, f, indent=4)
        
        
    return render(request, 'tai/tai2.html')

def tai3(request):
    return render(request, 'tai/tai.html')

def tai4(request):
    return render(request, 'tai/tai.html')




def connections():
    try:
        conn=ora.connect('ora_user01/1234@localhost:1521/orcl')
    except Exception as e:
        print('예외 발생')
    return conn

def chart_data(request):
    # city = request.GET.get('occur_city')
    sql = "select occur_mn, COUNT(*) from TAI_TACHART where OCCUR_PROVIN = '강서구' group by occur_mn order by occur_mn"
    print('sql :',sql)
    conn = connections()
    cs = conn.cursor()
    cs.execute(sql)
    rows = cs.fetchall()
    print('rs :', rows)
    
    context = {'result':rows}
    with open('static/data7.json', 'w') as f : 
        json.dump(rows, f, indent=4)
        
    return JsonResponse(context)

    
    
    

TAIS/midpjt_0307/templates/tai/tai.html
{% extends 'base.html' %}
{% block content %}
{% load static %}

<span style="font-size:30px;cursor:pointer " onclick="openNav()">&#9776; open</span>
<div class="fh5co-blog-style-1">
    <div class="container" style="margin-top: -50px ; ">
        <div class="text-center">
            <h2 class="fh5co-heading wow fadeInUp" data-wow-duration="1s" data-wow-delay=".5s">차트
                <span>
                    <form action="{% url 'tai:tai'%}" method="get">
                        <input type="text" name="name" style="position: relative; z-index: 999;">
                        <input type="submit" value="검색" style="position: relative; z-index: 999;">
                    </form>
                </span>
            </h2>
        </div>
        <div id="mySidenav" class="sidenav">
            <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
            <a href="{% url 'tai:tai'%}">차트1</a>
            <a href="{% url 'tai:tai'%}">차트2</a>
            <a href="{% url 'tai:tai'%}">차트3</a>
            <a href="{% url 'tai:tai'%}">차트4</a>
        </div>

        <div style="border: 1px solid black; width: 100%; height: 1200px; margin-bottom: 20px; margin-top: -70px; margin-top: 20px;">
            <div id="grape" style=" height: 350px; width: 45%; float: left; margin-left: 20px; margin-top: 20px; position: relative; z-index: 999;" >
                차트데이터1
                    <canvas id="myChart"  >
                    </canvas>
            </div>
            <div id="grape" style=" height: 350px; width: 45%; float: left; margin-left: 20px; margin-top: 20px; position: relative;">
                차트데이터2
                <canvas id="myChart2"  >
                </canvas>
            </div>
            <div id="grape" style=" height: 350px; width: 45%; float: left; margin-left: 20px; margin-top: 20px; position: relative;">
                차트데이터3
                <canvas id="myChart3"  >
                </canvas>
            </div>
            <div id="grape" style=" height: 350px; width: 45%; float: left; margin-left: 20px; margin-top: 20px; position: relative;">
                차트데이터4
                <canvas id="myChart4"  >
                </canvas>
            </div>
        </div>
    </div>
</div>
<script>
    function openNav() {
        document.getElementById("mySidenav").style.width = "250px";
        document.getElementById("mySidenav").style.marginTop = "100px";
    }
    function closeNav() {
        document.getElementById("mySidenav").style.width = "0";
    }
    function divopen(){
        document.getElementById("mySidenav").style.width = "250px";
        document.getElementById("mySidenav").style.marginTop = "100px";
    }



    $(function () {
            $.ajax({
                url: "{% static 'data1.json'%}",
                type: "get",
                data: {},
                dataType: "json",
                success: function (data) {
                    chartLabels = [];
                    chartData = [];
                    var i = 0
                    var j = 0
                    $.each(data,function(key,value){
                        chartLabels.push(data[i++][0]); //[2015,2016,2017,2018,2019,2020,2021]
                        chartData.push(data[j++][1]); //[1300,...]
                        
                    });
                    shapeChartDate = {
                        labels: chartLabels,
                        datasets: [{
                            label: '지역 그래프',
                            data: chartData,
                            backgroundColor: [
                            '#336580', '#336580','#336580','#336580','#336580','#336580','#336580','#336580',
                            '#336580', '#336580','#336580','#336580','#336580','#336580','#336580','#336580',
                            '#336580', '#336580','#336580','#336580','#336580','#336580','#336580','#336580','#336580',
                            ],
                            borderColor: [
                            '#336580'
                            ],
                            borderWidth: 1
                        }]
                    }
                    createChart();
                },
                error: function () {
                }
            });
            $.ajax({
                url: "{% static 'data2.json'%}",
                type: "get",
                data: {},
                dataType: "json",
                success: function (data) {
                    chartLabels = [];
                    chartData = [];
                    var i = 0
                    $.each(data,function(key,value){
                        chartLabels.push(data[i]); //[2015,2016,2017,2018,2019,2020,2021]
                        chartData.push(data[i++][1]); //[1300,...]
                    });
                    shapeChartDate = {
                        labels: chartLabels,
                        datasets: [{
                            label: '월별 그래프',
                            data: chartData,
                            backgroundColor: [
                            '#336580', '#B3E4FF', '#65CAFF', '#597280', '#52A1CC', '#204680', '#8CBAFF', '#408CFF', '#465D80', '#3270CC', '#242A80','#949BFF'
                                
                            ],
                            borderColor: [
                            '#336580', '#B3E4FF', '#65CAFF', '#597280', '#52A1CC', '#204680', '#8CBAFF', '#408CFF', '#465D80', '#3270CC', '#242A80','#949BFF'
                                
                            ],
                            borderWidth: 1
                        }]
                    }
                    createChart2();
                },
                error: function () {
                }
            });
            $.ajax({
                url: "{% static 'data3.json'%}",
                type: "get",
                data: {},
                dataType: "json",
                success: function (data) {
                    chartLabels = [];
                    chartData = [];
                    var i = 0
                    $.each(data,function(key,value){
                        chartLabels.push(data[i][0]); //[2015,2016,2017,2018,2019,2020,2021]
                        chartData.push(data[i++][1]); //[1300,...]
                    });
                    shapeChartDate = {
                        labels: chartLabels,
                        datasets: [{
                            label: '시간별 그래프',
                            data: chartData,
                            backgroundColor: [
                            '#336580', '#336580','#336580','#336580','#336580','#336580','#336580','#336580',
                            '#336580', '#336580','#336580','#336580','#336580','#336580','#336580','#336580',
                            '#336580', '#336580','#336580','#336580','#336580','#336580','#336580','#336580','#336580',
                            ],
                            borderColor: [
                            '#336580', '#B3E4FF', '#65CAFF', '#597280', '#52A1CC', '#204680', '#8CBAFF', '#408CFF', '#465D80', '#3270CC', '#242A80','#949BFF'
                            ],
                            borderWidth: 1
                        }]
                    }
                    createChart3();
                },
                error: function () {
                }
            });
            $.ajax({
                url: "{% static 'data4.json'%}",
                type: "get",
                data: {},
                dataType: "json",
                success: function (data) {
                    alert(data)
                    chartLabels = [];
                    chartData = [];
                    var i = 0
                    $.each(data,function(key,value){
                        chartLabels.push(data[i]); //[2015,2016,2017,2018,2019,2020,2021]
                        chartData.push(data[i++][1]); //[1300,...]
                    });
                    shapeChartDate = {
                        labels: chartLabels,
                        datasets: [{
                            label: '연령별 그래프',
                            data: chartData,
                            backgroundColor: [
                                '#336580', '#B3E4FF', '#65CAFF', '#597280', '#52A1CC', '#204680', '#8CBAFF', '#408CFF', '#465D80', '#3270CC', '#242A80','#949BFF'
                            ],
                            borderColor: [
                                '#336580', '#B3E4FF', '#65CAFF', '#597280', '#52A1CC', '#204680', '#8CBAFF', '#408CFF', '#465D80', '#3270CC', '#242A80','#949BFF'
                            ],
                            borderWidth: 1
                        }]
                    }
                    createChart4();
                },
                error: function () {
                }
            });
        
    });
    //차트 그리기
    function createChart() {
        const ctx = document.getElementById('myChart').getContext('2d');
        const myChart = new Chart(ctx, {
            type: 'bar',
            data: shapeChartDate,
            options: {
                scales: {
                    y: {
                        beginAtZero: true
                    }
                }
            }
        });
    }
    function createChart2() {
        const ctx = document.getElementById('myChart2').getContext('2d');
        const myChart2 = new Chart(ctx, {
            type: 'bar',
            data: shapeChartDate,
            options: {
                scales: {
                    y: {
                        beginAtZero: true
                    }
                }
            }
        });
    }
    function createChart3() {
        const ctx = document.getElementById('myChart3').getContext('2d');
        const myChart3 = new Chart(ctx, {
            type: 'bar',
            data: shapeChartDate,
            options: {
                scales: {
                    y: {
                        beginAtZero: true
                    }
                }
            }
        });
    }
    function createChart4() {
        const ctx = document.getElementById('myChart4').getContext('2d');
        const myChart4 = new Chart(ctx, {
            type: 'bar',
            data: shapeChartDate,
            options: {
                scales: {
                    y: {
                        beginAtZero: true
                    }
                }
            }
        });
    }
</script>
{% endblock %}

TAIS/midpjt_0307/templates/tai/tai2.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<script>
    function searchBtn(){
      if ($("#searchword").val().length <= 1){
        alert('검색어를 입력하셔야 검색이 가능합니다.(2자 이상)') ;
        return false ;
      }else{
        $("#search").submit()
      }
    }
  </script>
<span style="font-size:30px;cursor:pointer " onclick="openNav()">&#9776; open</span>
<div class="fh5co-blog-style-1">
    <div class="container" style="margin-top: -50px ; ">
        <div class="text-center">
            <h2 class="fh5co-heading wow fadeInUp" data-wow-duration="1s" data-wow-delay=".5s">차트
            </h2>
        </div>
        <div id="mySidenav" class="sidenav">
            <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
            <a href="{% url 'tai:tai'%}">전체</a>
            <a href="{% url 'tai:tai2'%}">차트2</a>
            <a href="{% url 'tai:tai3'%}">차트3</a>
            <a href="{% url 'tai:tai4'%}">차트4</a>
        </div>

        <div style="border: 1px solid black; width: 100%; height: 1200px; margin-bottom: 20px; margin-top: -70px; margin-top: 20px;">
            <div id="grape" style=" height: 350px; width: 45%; float: left; margin-left: 20px; margin-top: 20px; position: relative;" >
                차트데이터1
                    <canvas id="myChart"  >
                    </canvas>
            </div>
            <div id="grape" style=" height: 350px; width: 45%; float: left; margin-left: 20px; margin-top: 20px; position: relative;">
                차트데이터2
                <canvas id="myChart2"  >
                </canvas>
            </div>
            <div id="grape" style=" height: 350px; width: 45%; float: left; margin-left: 20px; margin-top: 20px; position: relative;">
                차트데이터3
                <canvas id="myChart3"  >
                </canvas>
            </div>
            <div id="grape" style=" height: 350px; width: 45%; float: left; margin-left: 20px; margin-top: 20px; position: relative;">
                차트데이터4
                <canvas id="myChart4"  >
                </canvas>
            </div>
        </div>
    </div>
</div>
<script>
    function openNav() {
        document.getElementById("mySidenav").style.width = "250px";
        document.getElementById("mySidenav").style.marginTop = "100px";
    }
    function closeNav() {
        document.getElementById("mySidenav").style.width = "0";
    }
    function divopen(){
        document.getElementById("mySidenav").style.width = "250px";
        document.getElementById("mySidenav").style.marginTop = "100px";
    }



    $(function () {
            $.ajax({
                url: "{% static 'data2.json'%}",
                type: "get",
                data: {},
                dataType: "json",
                success: function (data) {
                    chartLabels = [];
                    chartData = [];
                    alert(data)
                    var i = 0
                    $.each(data,function(key,value){
                        chartLabels.push(data[i][0]); //[2015,2016,2017,2018,2019,2020,2021]
                        chartData.push(data[i++][1]); //[1300,...]
                    });
                    shapeChartDate = {
                        labels: chartLabels,
                        datasets: [{
                            label: '월별 그래프',
                            data: chartData,
                            backgroundColor: [
                                'rgba(255, 99, 1, 0.2)',
                                'rgba(153, 102, 255, 0.32, 0.2)',
                                'rgba(54, 162, 235, 0.2)',
                                'rgba(255, 206, 86, 0.2)',
                                'rgba(75, 192, 1922)',
                                'rgba(255, 159, 64, 0.2)'
                            ],
                            borderColor: [
                                'rgba(255, 99, 132, 1)',
                                'rgba(54, 162, 235, 1)',
                                'rgba(255, 206, 86, 1)',
                                'rgba(75, 192, 192, 1)',
                                'rgba(153, 102, 255, 1)',
                                'rgba(255, 159, 64, 1)'
                            ],
                            borderWidth: 1
                        }]
                    }
                    createChart();
                },
                error: function () {
                }
            });
            $.ajax({
                url: "{% static 'data2.json'%}",
                type: "get",
                data: {},
                dataType: "json",
                success: function (data) {
                    chartLabels = [];
                    chartData = [];
                    var i = 0
                    $.each(data,function(key,value){
                        chartLabels.push(data[i][0]); //[2015,2016,2017,2018,2019,2020,2021]
                        chartData.push(data[i++][1]); //[1300,...]
                    });
                    shapeChartDate = {
                        labels: chartLabels,
                        datasets: [{
                            label: '지역 그래프',
                            data: chartData,
                            backgroundColor: [
                                'rgba(255, 99, 1, 0.2)',
                                'rgba(153, 102, 255, 0.32, 0.2)',
                                'rgba(54, 162, 235, 0.2)',
                                'rgba(255, 206, 86, 0.2)',
                                'rgba(75, 192, 1922)',
                                'rgba(255, 159, 64, 0.2)'
                            ],
                            borderColor: [
                                'rgba(255, 99, 132, 1)',
                                'rgba(54, 162, 235, 1)',
                                'rgba(255, 206, 86, 1)',
                                'rgba(75, 192, 192, 1)',
                                'rgba(153, 102, 255, 1)',
                                'rgba(255, 159, 64, 1)'
                            ],
                            borderWidth: 1
                        }]
                    }
                    createChart2();
                },
                error: function () {
                }
            });
            $.ajax({
                url: "{% static 'data3.json'%}",
                type: "get",
                data: {},
                dataType: "json",
                success: function (data) {
                    chartLabels = [];
                    chartData = [];
                    $.each(data,function(key,value){
                        chartLabels.push(value.weath_info);
                        chartData.push(value.dcount);
                    });
                    shapeChartDate = {
                        labels: chartLabels,
                        datasets: [{
                            label: '날씨 그래프',
                            data: chartData,
                            backgroundColor: [
                                'rgba(255, 99, 1, 0.2)',
                                'rgba(153, 102, 255, 0.32, 0.2)',
                                'rgba(54, 162, 235, 0.2)',
                                'rgba(255, 206, 86, 0.2)',
                                'rgba(75, 192, 1922)',
                                'rgba(255, 159, 64, 0.2)'
                            ],
                            borderColor: [
                                'rgba(255, 99, 132, 1)',
                                'rgba(54, 162, 235, 1)',
                                'rgba(255, 206, 86, 1)',
                                'rgba(75, 192, 192, 1)',
                                'rgba(153, 102, 255, 1)',
                                'rgba(255, 159, 64, 1)'
                            ],
                            borderWidth: 1
                        }]
                    }
                    createChart3();
                },
                error: function () {
                }
            });
            $.ajax({
                url: "{% static 'data4.json'%}",
                type: "get",
                data: {},
                dataType: "json",
                success: function (data) {
                    chartLabels = [];
                    chartData = [];
                    $.each(data,function(key,value){
                        chartLabels.push(value.occur_road_name_yn);
                        chartData.push(value.dcount);
                    });
                    shapeChartDate = {
                        labels: chartLabels,
                        datasets: [{
                            label: '도로별 그래프',
                            data: chartData,
                            backgroundColor: [
                                'rgba(255, 99, 1, 0.2)',
                                'rgba(153, 102, 255, 0.32, 0.2)',
                                'rgba(54, 162, 235, 0.2)',
                                'rgba(255, 206, 86, 0.2)',
                                'rgba(75, 192, 1922)',
                                'rgba(255, 159, 64, 0.2)'
                            ],
                            borderColor: [
                                'rgba(255, 99, 132, 1)',
                                'rgba(54, 162, 235, 1)',
                                'rgba(255, 206, 86, 1)',
                                'rgba(75, 192, 192, 1)',
                                'rgba(153, 102, 255, 1)',
                                'rgba(255, 159, 64, 1)'
                            ],
                            borderWidth: 1
                        }]
                    }
                    createChart4();
                },
                error: function () {
                }
            });
        
    });
    //차트 그리기
    function createChart() {
        const ctx = document.getElementById('myChart').getContext('2d');
        const myChart = new Chart(ctx, {
            type: 'bar',
            data: shapeChartDate,
            options: {
                scales: {
                    y: {
                        beginAtZero: true
                    }
                }
            }
        });
    }
    function createChart2() {
        const ctx = document.getElementById('myChart2').getContext('2d');
        const myChart2 = new Chart(ctx, {
            type: 'pie',
            data: shapeChartDate,
            options: {
                scales: {
                    y: {
                        beginAtZero: true
                    }
                }
            }
        });
    }
    function createChart3() {
        const ctx = document.getElementById('myChart3').getContext('2d');
        const myChart3 = new Chart(ctx, {
            type: 'bar',
            data: shapeChartDate,
            options: {
                scales: {
                    y: {
                        beginAtZero: true
                    }
                }
            }
        });
    }
    function createChart4() {
        const ctx = document.getElementById('myChart4').getContext('2d');
        const myChart4 = new Chart(ctx, {
            type: 'bar',
            data: shapeChartDate,
            options: {
                scales: {
                    y: {
                        beginAtZero: true
                    }
                }
            }
        });
    }
</script>
{% endblock %}