TAIS/midpjt_0307/fboard/urls.py
from . import views
from django.urls import path 

app_name = 'fboard'

urlpatterns = [
    path('notification/', views.notification, name='notification'),
    path('notification_view/', views.notification_view, name='notification_view'),
    path('news/', views.news, name='news'),
    path('news_page/', views.news_page, name='news_page'),
]

TAIS/midpjt_0307/midpjt/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('member/', include('member.urls')),
    path('fboard/', include('fboard.urls')), 
    path('comm/', include('comm.urls')), 
    path('event/', include('event.urls')), 
    path('tai/', include('tai.urls')), 
]

TAIS/midpjt_0307/tai/urls.py
from . import views
from django.urls import path 

app_name = 'tai'

urlpatterns = [
    path('tai/', views.tai, name='tai'),
    path('tai2/', views.tai2, name='tai2'),
]

TAIS/midpjt_0307/fboard/models.py
from datetime import datetime
from django.db import models


class Related_Info(models.Model) : # 연관 정보 db
    accident_no =  models.CharField(max_length = 8) # 사고 일련번호 --
    news_code_no =  models.CharField(max_length = 8) # 뉴스 일련번호 --
    news_info = models.CharField(max_length = 50) # 뉴스 정보
    accident_info = models.CharField(max_length = 50) # 사고정보(키워드 등...)
    
    def __str__(self) :
        return self.news_info
    
class News_Info(models.Model) : # 뉴스정보 db
    news_no = models.CharField(max_length = 8) # 뉴스 일련번호 --
    news_kind = models.CharField(max_length = 10) # 뉴스 구분
    news_date = models.DateTimeField(default = datetime.now(), blank = True) # 뉴스 일자
    news_content = models.TextField() # 뉴스 내용
    news_keyword = models.CharField(max_length = 50) # 뉴스 키워드
    weather_info = models.CharField(max_length = 20) # 날씨 정보
    news_img = models.ImageField(blank=True) # 뉴스 페이지 이미지
    
    def __str__(self) :
        return self.news_keyword
    
class Notice(models.Model) : # 공지사항 db 생성
    notice_title = models.CharField(max_length = 50) # 공지사항 타이틀
    notice_content = models.TextField() # 공지사항 내용
    notice_dt = models.DateTimeField(default = datetime.now(), blank = True) # 등록일자
    notice_cnt = models.IntegerField(default=1) # 조회수
    notice_img = models.ImageField(blank=True) # 공지사항 페이지 이미지
    
    def __str__(self) :
        return self.notice_title

TAIS/midpjt_0307/fboard/views.py
from django.shortcuts import render
import urllib.request
import requests
from bs4 import BeautifulSoup
from PIL import Image
from fboard.models import News_Info

# Create your views here.
def notification(request):
    return render(request, 'fboard/notification.html')

def notification_view(request):
    return render(request, 'fboard/notification_view.html')

def news(request):
    qs = News_Info.objects.all()
    qs.delete()
    
    firms = ["교통"]
    for firm in firms:
        url = f"https://search.naver.com/search.naver?where=news&sm=tab_jum&query={firms}"
        res = requests.get(url)
        res.raise_for_status()
        soup = BeautifulSoup(res.text, "lxml")
        soup_tit = soup.find_all("a", attrs={"class": "news_tit"})
        soup_info = soup.find_all("span", attrs={"class": "info"})
        soup_img =  soup.find_all("img",attrs = {"class":"thumb api_get"})
    #     dates = [ date.get_text() for date in soup.find_all('span', attrs={'class':'info'})] # 기사 작성일
        indx =0
        for tit, time,img in zip(soup_tit, soup_info,soup_img):
            if firm in tit.get_text():
                tit_box = []
                url_box = []
                img_box = []
    #             print(f"{tit.get_text()} {info.get_text()} {tit['href']}")
                print(tit.get_text())
                print(time.get_text())
                print(tit['href'])
                print(img['src'])
                indx +=1
                urllib.request.urlretrieve(img['src'], "이미지{}.jpg".format(indx))
                news_img = "이미지{}.jpg".format(indx)
                print(news_img)
                tit_box.append(tit.get_text())
                url_box.append(tit['href'])
                news_keyword = tit_box[0]
                news_content = url_box[0]
                qs = News_Info(news_keyword=news_keyword, news_img=news_img, news_content=news_content)
                qs.save()
    # news_img = img_box[0]
    
    # qs = News_Info(news_keyword=news_keyword, news_img=news_img, news_no='1',news_kind='1',news_content='1', weather_info='1' )
    
    return render(request, 'fboard/news.html')

# def community(request):
#     return render(request, 'community.html')

def news_page(request):
    return render(request, 'fboard/news_page.html')

TAIS/midpjt_0307/templates/fboard/news.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/news.css' %}">
<div class="fh5co-heading wow fadeInUp" data-wow-duration="1s" data-wow-delay=".5s">			
	<div style="text-align:center;">
		<h2>뉴스</h2>
	</div>
</div>
<section id="news_div">
	<div id="news_div0">
		<div id="news_subdiv1">
			<div id="news_sdivimg">
				<img style="width: 400px; height: 195px; object-fit: cover;" src="{% static 'images/newsimg1.png' %}" alt="뉴스1">
			</div>
		</div>
		<div id="news_subdiv2">	
			<div class = "news_title">
				<span id="ntitle">
					<img src = "//tr-image.game.onstove.com/web/Common/Icons/ico_event_ing.gif" width = '41' height = '14' alt = "진행중">
				</span> 
				<a href="{% url 'fboard:news_page' %}" style="text-decoration: none; position:relative; z-index:9999;">자동차안전단속, 야간운전 적 ‘등화장치위반’ 53.2%</a>
			</div>
			<div class = "news_days">
				<span id="ndays">
					<img src = "{% static 'images/days_icon2.gif' %}" width = '4' height = '5' alt = ">">
				</span> 
				등록일자 : 2022-02-24 13:15
			</div>
			<div class = "news_content"><a href="{% url 'fboard:news_page' %}">
				<h3>한국교통안전공단 2021년 13,679대 적발</h3>
				<br>
				출처 : 교통뉴스(http://www.cartvnews.com)</a>
			</div>
		</div>
	</div>
	<div id="news_div0">
		<div id="news_subdiv1">
			<div id="news_sdivimg">
				<img style="width: 400px; height: 195px; object-fit: cover;" src="{% static 'images/newsimg2.png' %}" alt="뉴스1">
			</div>
		</div>
		<div id="news_subdiv2">	
			<div class = "news_title">
				<span id="ntitle">
					<img src = "//tr-image.game.onstove.com/web/Common/Icons/ico_event_ing.gif" width = '41' height = '14' alt = "진행중">
				</span> 
				<a href="{% url 'fboard:news_page' %}">행안부, 교통사고 잦은 곳 개선하니 사망자 및 교통사고 줄어</a>
			</div>
			<div class = "news_days">
				<span id="ndays">
					<img src = "{% static 'images/days_icon2.gif' %}" width = '4' height = '5' alt = ">">
				</span> 
				등록일자 : 2022-02-22 13:45 
			</div>
			<div class = "news_content"><a href="{% url 'fboard:news_page' %}">
				<h3>지난해까지 11,803개소 개선</h3>
				<br>
				출처 : 교통뉴스(http://www.cartvnews.com)</a>
			</div>
		</div>
	</div>
	<div id="news_div0">
		<div id="news_subdiv1">
			<div id="news_sdivimg">
				<img style="width: 400px; height: 195px; object-fit: cover;" src="{% static 'images/newsimg3.png' %}" alt="뉴스1">
			</div>
		</div>
		<div id="news_subdiv2">	
			<div class = "news_title">
				<span id="ntitle">
					<img src = "//tr-image.game.onstove.com/web/Common/Icons/ico_event_ing.gif" width = '41' height = '14' alt = "진행중">
				</span> 
				<a href="{% url 'fboard:news_page' %}">양평군 ‘23년공공하수처리시설’ 신·증설사업 국비신청</a>
			</div>
			<div class = "news_days">
				<span id="ndays">
					<img src = "{% static 'images/days_icon2.gif' %}" width = '4' height = '5' alt = ">">
				</span> 
				등록일자 : 2022-03 
			</div>
			<div class = "news_content"><a href="{% url 'fboard:news_page' %}">
				<h3>전액확보 2030년인구증가 약 16만명 처리가능</h3>
				<br>
				출처 : 교통뉴스(http://www.cartvnews.com)</a>
			</div>
		</div>
	</div>
</section>

{% endblock  %}

TAIS/midpjt_0307/templates/fboard/news_page.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<link rel="stylesheet" href={% static 'css/news_page.css' %}
<body>
	<div class="">
		<div class="container">
			<div class = "new_page_div">
				{% comment %} <div class = "new_page_icon">
					아이콘 넣기
				</div> {% endcomment %}
				<div class = "new_page_title">
					자동차안전단속, 야간운전 적 ‘등화장치위반’ 53.2%
				</div>
				<div class = "new_page_day">
					2022-02-24 13:15
				</div>
				<div class = "new_page_reporter">
					TAIS 운영자
				</div>
				{% comment %} <div class = "new_page_good_icon">
					아이콘 같은거 넣음
					<span style = "margin-left: -100px; margin-top : 10px">
						<img src = "//tr-image.game.onstove.com/web/Common/Icons/ico_event_ing.gif" width = '41' height = '14' alt = "진행중">
					</span> 
				</div> {% endcomment %}
				<div class = "new_page_photo">
					<img src="{% static 'images/newsimg1.png' %}">
				</div>
				<div class = "new_page_content">
					2021년 자동차안전단속 결과를 분석한 한국교통안전공단에 따르면 지난 한 해 13,679대의 차량 대상으로 위반사항 20,477건을 단속했고, 전체 항목 중에서는 등화장치 관련 위반이 10,902건으로 53.2%를 차지했다고 한다.
				<br>
                    안전과 직결되는 이런 위반 사안은 최근 사회적 문제로 대두되고 있는 ‘이륜차 교통법규 위반 행위’에 대한 관계기관과의 집중단속을 강화한 결과라고 덧붙였다.
				<br>
					가장 중시돼야 할 안전기준 위반 항목에서는 4,221건이 등화 장치 손상차로 적발돼 27.6%를 차지한 반면에 이륜차 불법등화설치 1,301건으로 86.7%에 상당하는 이륜차들이 등화 관련 항목 적발건수가 많았다.
				<br>
					<img src="{% static 'images/newssubimg1.png' %}">
				<br>
					유형별 단속은 82.1%에 달하는 자동차와 이륜차 안전기준 위반 적발건수 16,807건이 가장 많았고, 2,999건인 불법 튜닝 비율은 14.6%, 등록번호판 등의 위반 671건은 3.3%로 이어졌다.
				<br>
					불법튜닝 항목에서는 자동차는 물품적재장치 임의 변경과 좌석 탈거 등 승차 장치임의 변경이 각각 639건(33.1%), 504건(26.1%)으로 위반 비율이 가장 많았고, 뒤를 이은 이륜차는 소음기 개조 586건(54.8%), 등화장치 임의 변경408건(38.1%) 순으로 적발됐다.
				<br>
					등록번호판 등 위반 항목에서는 자동차와 이륜차 모두 번호판 식별 불가가 각각 188건(45.0%), 130건(51.4%)으로 높았다.
				<br>
					전체 단속 항목 중에서 높은 비중을 차지하고 있는 자동차와 이륜차 등화 장치 관련 위반사항은 각각 51.2%(9,045건), 65.8%(1,857건)에 달했다.
				<br>
					위험한 야간 운행으로 몰고 가는 등화 손상과 불법 등화 설치 등은 야간 주행 시 차량 식별 불가와 상대방 운전자의 눈부심을 유발하는 등 교통사고의 원인이 될 수 있어 상시 관리가 요구된다.
				<br>
					그 외에도, 화물차에 설치된 후부 반사판 및 안전판 관련 위반이 자동차 전체 적발건수의 19.3%(3,410건)로 높게 나타났고, 후부 안전판은 화물차 충돌사고 시 후방 차량 피해를 줄이기 위한 장치로 빛 반사 능력과 높이, 길이 등 안전기준에 맞게 설치돼 한다.

					아울러 이륜차 또한 소음기 개조 위반 항목이 전체 적발건수의 20.8%(586건) 수준을 기록하고 있어, 운전자의 튜닝 기준 준수가 요구되고 있다.
				<br>
					자동차안전단속은 ‘안전기준 위반’과 ‘불법튜닝’ 등 자동차관리법을 위반한 차량이 다른 차량 운행을 방해하거나, 위험을 초래할 수 있는 위험요인을 색출해서 사전 제거를 통해 교통안전을 확보하기 위하는 데 있다.
				<br>
					교통안전공단은 2005년부터 국토부와 경찰청, 지자체 등과 합동 단속업무를 시행하고 있고, 2018년부터는 자동차관리법 개정에 따라 자동차안전기준 적합 여부에 대해서도 공단이 독자적 단속을 수행하고 있다.
				<br>
					각 항목별 위반으로 단속될 경우, 불법튜닝은 원상 복구해야 하는 임시검사 명령과 1년 이하 징역 또는 1,000만 원 이하의 벌금 부과되고, 안전기준 위반사항은 100만 원 이하의 과태료 부과와 점검·정비 또는 원상 복구명령이 내려진다.
				<br>
					등록번호판 등 위반은 1년 이하의 징역 또는 1,000만 원 이하의 벌금형(위·변조의 경우 10년 이하의 징역·1억 원 이하 벌금형)에 처 해지는 점을 강조한 권용복 이사장은 “안전기준에 적합하지 않은 차량은 다른 차량에 영향을 주기 때문에 국민의 안전뿐 아니라 생활환경까지 위협할 수 있다”고 말했다.
				<br>
					2021년 자동차안전단속 결과(통계)는 한국교통안전공단 홈페이지에서 확인할 수 있고, 계속해서 국토부와 경찰청, 지자체 등의 관계기관 협업을 통한 자동차안전단속 확대로 국민들이 안전할 수 있는 교통환경을 만들어나갈 것을 약속했다.
				<br>
					출처 : 교통뉴스(http://www.cartvnews.com)
				</div>
				<hr style="border:1px solid silver;">
			</div>
		</div>
	</div>	
	
</body>

		 
		  
			
	
{% endblock  %}

TAIS/midpjt_0307/templates/fboard/notification.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/notification.css' %}">
<div class="fh5co-blog-style-1">
    <div class="container">
        <div class="board_list_wrap">
            <h2 class="fh5co-heading wow fadeInUp" data-wow-duration="1s" data-wow-delay=".5s">공지사항
            </h2>
            <div class="board_list">
                <div class="board_list_head">
                    <div class="no_num">번호</div>
                    <div class="no_tit">제목</div>
                    <div class="no_writer">글쓴이</div>
                    <div class="no_date">작성일</div>
                    <div class="no_view">조회</div>
                </div>
                <div class="board_list_body">
                    <div class="item">
                        <div class="no_num">1</div>
                        <div class="no_tit"><a href="{% url 'fboard:notification_view' %}">홈페이지 오픈준비중입니다.</a></div>
                        <div class="no_writer">TAIS 운영자</div>
                        <div class="no_date">2022-03-08</div>
                        <div class="no_view">111</div>
                    </div>
                </div>
            </div>
            <div class="paging">
                <!-- <a href="#" class="bt first">처음 페이지</a>
                <a href="#" class="bt prev">이전 페이지</a> -->
                <a href="#" class="num on">1</a>
                <a href="#" class="num">2</a>
                <a href="#" class="num">3</a>
                <!-- <a href="#" class="bt next">다음 페이지</a>
                <a href="#" class="bt last">마지막 페이지</a> -->
            </div>
        </div>
    </div>
</div>
{% endblock %}

TAIS/midpjt_0307/templates/fboard/notification_view.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/notification_view.css' %}">
<div class="fh5co-blog-style-1">
    <div class="container">
        <section>
            <h1>TAIS</h1>
            <table>
              <colgroup>
                <col width="80%">
                <col width="10%">
                <col width="10%">  
              </colgroup>
              <tr>
                <th colspan="3">제목</th>
              </tr>
              <tr>
                <td colspan="3"><strong>홈페이지 오픈준비중입니다.</strong></td>
              </tr>
              <tr>
                <td>TAIS 운영자</td>
                <td>조회수</td>
                <td>112</td>
              </tr>
              <tr>
                <td colspan="3" class="article">
                  서버 내 문제가 생겨 잠시 연기하겠습니다.
                  <br>
                  불편을 드려 대단히 죄송합니다.
                </td>
              </tr>
            </table>
            <a href=""><div class="list">목록</div></a>
          </section>
    </div>
</div>
{% endblock %}