midpjt/comm/urls.py
from . import views
from django.urls import path 

app_name = 'comm'

urlpatterns = [
    path('community/', views.community, name='community'),
    path('<str:board_no>/community_view/', views.community_view, name='community_view'),
    path('community_write/', views.community_write, name='community_write'),
    path('community_writeOk/', views.community_writeOk, name='community_writeOk'),
]

midpjt/midpjt/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('member/', include('member.urls')),
    path('fboard/', include('fboard.urls')), 
    path('comm/', include('comm.urls')), 
    path('event/', include('event.urls')), 
    path('tai/', include('tai.urls')), 
]

midpjt/tai/urls.py
from . import views
from django.urls import path 

app_name = 'tai'

urlpatterns = [
    path('tai/', views.tai, name='tai'),
]

midpjt/comm/models.py
from datetime import datetime
from django.db import models
from member.models import User_Info

class Board(models.Model) : # 게시판 db 생성 / 자유게시판, 공지, 1대1 문의
    user_id = models.ForeignKey(User_Info, on_delete = models.DO_NOTHING, null = True) # member models에서 참조하는 외래키 사용자 아이디
    b_kind = models.CharField(max_length = 10) # 게시글 분류
    board_no = models.IntegerField(default = 1, primary_key = True) # 게시판 일련번호
    b_title = models.CharField(max_length = 1000) # 게시글 제목
    b_content = models.TextField() # 게시글
    b_date = models.DateTimeField(default = datetime.now(), blank = True) # 일자
    b_count = models.IntegerField(default = 1) # 조회수
    b_group = models.IntegerField(default=0) # 답글
    b_step = models.IntegerField(default=0) # 답글
    b_indent = models.IntegerField(default=0) # 답글
    b_img = models.ImageField(blank=True) # 보드 이미지
    
    def __str__(self) :
        return self.b_title
    
class Comment(models.Model) : # 댓글 db 생성
    user_id = models.ForeignKey(User_Info, on_delete = models.CASCADE, null = True) # member models에서 참조하는 외래키 사용자 아이디
    comment_no = models.ForeignKey(Board, on_delete = models.CASCADE, null = True, default = 0) # 게시판 일련번호 Board의 board_no 참조
    comment_content = models.TextField() # 댓글 내용
    comment_dt = models.DateTimeField(default = datetime.now(), null = True, blank = True) #  댓글 작성 일자
    
    def __str__(self) :
        return self.comment_content
    
    

midpjt/comm/views.py
from django.shortcuts import redirect, render
from comm.models import Board
from member.models import User_Info  
from django.core.paginator import Paginator
from django.db.models import Q
from django.db.models import Max

# Create your views here.
def community(request):
    nowpage = int(request.GET.get('nowpage', 1))
    if request.method == 'GET' :
        qs = Board.objects.all().order_by('-b_group','-b_step')
        paginator = Paginator(qs,10)
        community = paginator.get_page(nowpage)
        context = {'community' : community, 'nowpage' : nowpage}
        return render(request,'comm/community.html',context)

    else :
        category = request.POST.get('category')
        searchword = request.POST.get('searchword')
        if category == 'title' :
            qs = Board.objects.filter(b_title__contains = searchword)
            paginator = Paginator(qs,10)
            community = paginator.get_page(nowpage)
            context = {'community' : community, 'nowpage' : nowpage, 'category' : category, 'searchword' : searchword}
            return render(request,'comm/community.html',context)
        elif category == 'content' :
            qs = Board.objects.filter(b_content__contains = searchword)
            paginator = Paginator(qs,10)
            community = paginator.get_page(nowpage)
            context = {'community' : community, 'nowpage' : nowpage, 'category' : category, 'searchword' : searchword}
            return render(request,'comm/community.html',context)
        elif category == 'all' :
            qs = Board.objects.filter(Q(b_title__contains = searchword) | Q(b_content__contains = searchword))
            paginator = Paginator(qs,10)
            community = paginator.get_page(nowpage)
            context = {'community' : community, 'nowpage' : nowpage,'category' : category, 'searchword' : searchword}
            return render(request,'comm/community.html',context)

def community_view(request, board_no):
    qs = Board.objects.get(board_no = board_no)
    qs.b_count += 1
    qs.save()
    context = {'community' : qs }
    
    return render(request, 'comm/community_view.html', context)

def community_write(request):
    return render(request, 'comm/community_write.html')
        
def community_writeOk(request) :
    id = request.POST.get('id')
    member = User_Info.objects.get(user_id = id)
    title = request.POST.get('title')
    content = request.POST.get('content')
    # img = request.FILES.get('img', '')
    no = User_Info.objects.aggregate(max_b_hit = Max('b_count'))
    max_no = no['max_b_no']
    max_no += 1
    b_no = max_no
    
    qs = Board(board_no = b_no, user_id=member, b_title=title, b_content=content)
    qs.save()

    return redirect('comm/community.html')

midpjt/templates/comm/community.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<script>
  function searchBtn(){
    if ($("#searchword").val().length <= 1){
      alert('검색어를 입력하셔야 검색이 가능합니다.(2자 이상)') ;
      return false ;
    }else{
      $("#search").submit()
    }
  }
</script>
<div>
<section>
  <h1>자유게시판</h1>
  <div class="wrapper">
    <form action="{% url 'comm:community' %}" id="search" method="post">
      {% csrf_token %}
      {% if category %}
      <select name="category" id="category">
        <option value="all" {% if category in 'all' %}selected{% endif %}>전체</option>
        <option value="title" {% if category in 'titlel' %}selected{% endif %}>제목</option>
        <option value="content" {% if category in 'content' %}selected{% endif %}>내용</option>
      </select>
      {% else %}
      <select name="category" id="category">
        <option value="all">전체</option>
        <option value="title">제목</option>
        <option value="content">내용</option>
      </select>
      {% endif %}

      <div class="title">
        {% if searchword %}
        <input type="text" id="searchword" name="searchword" size="16" value="{{searchword}}">
        {% else %}
        <input type="text" id="searchword" name="searchword" size="16">
        {% endif %}
      </div>
      <button type="button" onclick="searchBtn()"><i class="fas fa-search"></i></button>
    </form>
  </div>


  <table>
    <colgroup>
      <col width="15%">
      <col width="40%">
      <col width="15%">
      <col width="15%">
      <col width="15%">
    </colgroup>
    <!-- 제목부분 -->
    <tr>
      <th>No.</th>
      <th>제목</th>
      <th>작성일</th>
      <th>작성자</th>
      <th>조회수</th>
    </tr>
    <!-- 내용부분 -->
    <tbody id="tbody">
      {% if community %}
          {% for comm in community %}
            <tr>
              <td><span class='table-notice'>{{comm.board_no}}</span></td>
              <td class='table-title' id='pInput'>
                <a href="{% url 'comm:community_view' comm.board_no %}">
                </a>
              </td>
              <td>{{comm.b_date|date:'Y-m-d H:i'}}</td>
              <td>{{comm.user_id}}</td>
              <td>{{comm.b_count}}</td>
            </tr>
          {% endfor %}
        {% else %}
          <tr>
            <td colspan='5'>현재 데이터가 없습니다.</td>
          </tr>
        {% endif %}
    </table>

  <ul class="page-num">
    {% if community.has_previous %}
        <a href = "?nowpage=1"><li class="first"></li></a>
        <a href = "?nowpage={{ community.previous_page_number }}"><li class="prev"></li></a>
      {% else %}
        <li class="first"></li>
        <li class="prev"></li>
      {% endif %}
      
    {% for page in community.paginator.page_range %}
      {% if page != nowpage %}
        <a href = "?nowpage={{page}}"><li class="num off"><div>{{page}}</div></li></a>
      {% else %}
        <li class="num on"><div>{{page}}</div></li>
      {% endif %}
    {% endfor %}
    {% if community.has_next %}
      <a href = "?nowpage={{ community.next_page_number }}"><li class="next"></li></a>
      <a href = "?nowpage={{ community.paginator.num_pages }}"><li class="last"></li></a>
    {% else %}
      <li class="next"></li>
      <li class="last"></li>
    {% endif %}
  </ul>

  <div class="community_write">
    <a href="{% url 'comm:community_write' %}" class="community_button">
      쓰기
    </a>
  </div>
</section>
</div>
{% endblock  %}

midpjt/templates/comm/community_view.html
{%extends 'base.html' %}
{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/read.css' %}">
<section>
  <h1>자유게시판</h1>

  <table>
    <colgroup>
      <col width="80%">
      <col width="10%">
      <col width="10%">
      
    </colgroup>
    <tr>
      <th colspan="3">제목</th>
    </tr>
    <tr>
      <td colspan="3"><strong>게시판 글제목이 들어갑니다.</strong></td>
    </tr>
    <tr>
      <td>작성자가 들어갑니다.</td>
      <td>조회수</td>
      <td>111</td>
    </tr>
    <tr>
      <td colspan="3" class="article">글 내용이 들어갑니다.</td>
    </tr>
    <tr>
      <td colspan="3"><strong>다음글</strong> <span class="separator">|</span> [키즈잼] 2월 프로그램 안내</td>
    </tr>
    <tr>
      <td colspan="3"><strong>이전글</strong> <span class="separator">|</span> [키즈잼] 2020년 1분기 정기 휴관일 안내</td>
    </tr>
  </table>
  <div class="button-ul">
    <ul>
      <li>
        <a href=""><div class="list">목록</div></a>
      </li>
      <li>
        <a href=""><div class="list">삭제</div></a>
      </li>
      <li>
        <a href=""><div class="list">수정</div></a>
      </li>
      <li>
        <a href=""><div class="list">답변달기</div></a>
      </li>
    </ul>
  </div>
</section>
{% endblock %}

midpjt/templates/comm/community_write.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/write.css' %}">
<section>
  <h1>자유게시판</h1>
  <hr>

  <form action="write.do" name="write" method="post">
    <table>
      <colgroup>
        <col width="15%">
        <col width="85%">
      </colgroup>
      <tr>
        <th>작성자</th>
        <td>
          <input type="text" name="bName">
        </td>
      </tr>
      <tr>
        <th>제목</th>
        <td>
          <input type="text" name="bTitle">
        </td>
      </tr>
      <tr>
        <th>내용</th>
        <td>
          <textarea name="bContent" cols="50" rows="10"></textarea>
        </td>
      </tr>
      <tr>
        <th>이미지 표시</th>
        <td>
          <input type="file" name="file" id="file">
        </td>
      </tr>
    </table>
    <hr>
    <div class="button-wrapper">
      <ul class="button-ul">
        <li>
          <button type="submit" class="write">작성완료</button>
        </li>
        <li>
          <button type="button" class="cancel" onclick="javascript:location.href='../community/community.html'">취소</button>
        </li>
      </ul>
    </div>
  </form>
</section>
{% endblock %}