midpjt/comm/urls.py
from . import views
from django.urls import path 

app_name = 'comm'

urlpatterns = [
    path('community/', views.community, name='community'),
    path('<str:board_no>/community_view/', views.community_view, name='community_view'),
    path('community_write/', views.community_write, name='community_write'),
    path('community_writeOk/', views.community_writeOk, name='community_writeOk'),
]

midpjt/event/urls.py
from . import views
from django.urls import path 

app_name = 'event'

urlpatterns = [
    path('event/', views.event, name='event'),
    path('event_view/', views.event_view, name='event_view'),
]

midpjt/fboard/urls.py
from . import views
from django.urls import path 

app_name = 'fboard'

urlpatterns = [
    path('notification/', views.notification, name='notification'),
    path('notification_view/', views.notification_view, name='notification_view'),
    path('news/', views.news, name='news'),
    path('news_page/', views.news_page, name='news_page'),

]

midpjt/member/urls.py
from . import views
from django.urls import path 

app_name = 'member'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('addaccount/', views.addaccount, name='addaccount'),
]

midpjt/midpjt/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('member/', include('member.urls')),
    path('fboard/', include('fboard.urls')), 
    path('comm/', include('comm.urls')), 
    path('event/', include('event.urls')), 
    path('tai/', include('tai.urls')), 
]

midpjt/tai/urls.py
from . import views
from django.urls import path 

app_name = 'tai'

urlpatterns = [
    path('tai/', views.tai, name='tai'),
]

midpjt/templates/base.html
<!DOCTYPE html>
<html class="no-js" lang="ko" >
{% include 'head.html' %}
<body>
	{% include 'header.html' %}

    {% block content %}
    {% endblock  %}

    {% include 'footer.html' %}
    {% include 'js.html' %}
</body>
</html>

midpjt/templates/footer.html
{% load static %}
<!-- START footer -->
<div class="fh5co-footer-style-3">
    <div class="container">
        <div class="row p-b">
            <div class="col-md-3 col-sm-6 fh5co-footer-widget wow fadeInUp" data-wow-duration="1s" data-wow-delay=".5s">
                <div class="fh5co-logo"><span class="logo">TAIS</span> TAIS</div>
                <p class="fh5co-copyright">&copy; 2016 Voltage. <br>All Rights Reserved. <br>Designed by <a target="_blank" href="http://freehtml5.co">FREEHTML5.co</a> <br>Created with <a target="_blank" href="http://freehtml5.co/cards">Cards</a> <br> 
                    Images: <a target="_blank" href="http://unsplash.com/">Unsplash</a>, <a target="_blank" href="http://pexels.com/">Pexels</a></p>
            </div>
            <div class="col-md-3 col-sm-6 fh5co-footer-widget wow fadeInUp" data-wow-duration="1s" data-wow-delay=".8s">
                <h3>Company</h3>
                <ul class="fh5co-links">
                    <li><a href="#">How it Works</a></li>
                    <li><a href="#">Services</a></li>
                    <li><a href="#">Products</a></li>
                    <li><a href="#">Careers</a></li>
                    <li><a href="#">Blog</a></li>
                    <li><a href="#">Contact</a></li>
                </ul>
            </div>
            <div class="clearfix visible-sm-block"></div>
            <div class="col-md-3 col-sm-6 fh5co-footer-widget wow fadeInUp" data-wow-duration="1s" data-wow-delay="1.1s">
                <h3>Connect</h3>
                <ul class="fh5co-links fh5co-social">
                    <li><a href="#"><i class="icon icon-facebook2"></i> Facebook</a></li>
                    <li><a href="#"><i class="icon icon-twitter"></i> Twitter</a></li>
                    <li><a href="#"><i class="icon icon-dribbble"></i> Dribbble</a></li>
                    <li><a href="#"><i class="icon icon-instagram"></i> Instagram</a></li>
                </ul>
            </div>
            <div class="col-md-3 col-sm-6 fh5co-footer-widget wow fadeInUp" data-wow-duration="1s" data-wow-delay="1.4s">
                <h3>About</h3>
                <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. </p>
                <p><a href="#" class="btn btn-success btn-sm btn-outline">I'm a button</a></p>
            </div>
            <div class="clearfix visible-sm-block"></div>
        </div>
        <div class="row fh5co-made">
            <div class="col-md-12 wow fadeInUp" data-wow-duration="1s" data-wow-delay=".5s">
                <p>Made with <i class="heart icon-heart"></i> in Philippines</p>
            </div>
        </div>
    </div>
</div>
<!-- END footer -->

midpjt/templates/head.html
{% load static %}
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title>{% block title %}{% endblock %} - Simple Django</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="Free HTML5 Template by FREEHTML5.CO" />
	<meta name="keywords" content="free html5, free template, free bootstrap, html5, css3, mobile first, responsive" />
	<meta name="author" content="FREEHTML5.CO" />

	<meta property="og:title" content="" />
	<meta property="og:image" content="" />
	<meta property="og:url" content="" />
	<meta property="og:site_name" content="" />
	<meta property="og:description" content="" />
	<meta name="twitter:title" content="" />
	<meta name="twitter:image" content="" />
	<meta name="twitter:url" content="" />
	<meta name="twitter:card" content="" />

	<!-- Place favicon.ico and apple-touch-icon.png in the root directory -->
	<link rel="shortcut icon" href="favicon.ico">
	<!-- Google Fonts -->
	<link href='https://fonts.googleapis.com/css?family=Open+Sans:400,300,700|Monsterrat:400,700|Merriweather:400,300italic,700' rel='stylesheet' type='text/css'>
	<!-- Animate.css -->
	<link rel="stylesheet" href="{% static 'css/animate.css' %}">
	<!-- Icomoon Icon Fonts-->
	<link rel="stylesheet" href="{% static 'css/icomoon.css' %}">
	<!-- Magnific Popup-->
	<link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">
	<!-- Owl Carousel -->
	<link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
	<link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">
	<!-- Bootstrap  -->
	<link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
	<!-- Cards -->
	<link rel="stylesheet" href="{% static 'css/cards.css' %}">
	<!-- Community style -->
	<link rel="stylesheet" href="{% static 'css/community_style.css' %}">
	<link rel="stylesheet" href="{% static 'css/style.css' %}">
	<!-- Notice_list style 충돌때문에 필요시 링크복사할 것 -->

	<!-- Modernizr JS -->
	<script src="js/modernizr-2.6.2.min.js"></script>
</head>

midpjt/templates/header.html
{% load static %}
<!--START header-->
<div id="fh5co-page" class="community_logo">
    <nav class="fh5co-community-style-1" role="navigation" data-offcanvass-position="fh5co-offcanvass-left" style="background-image: url({% static 'images/full_2.jpg' %})">
        <div class="container">
            <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12 fh5co-logo">
                <a href="#" class="js-fh5co-mobile-toggle fh5co-nav-toggle"><i>아이콘</i></a>
                <a href="/">TAIS</a>
            </div>
            <div class="col-lg-6 col-md-5 col-sm-5 text-center fh5co-link-wrap">
                <ul data-offcanvass="yes" class="main1">
                    <li><a href="{% url 'tai:tai' %}">차트</a></li>
                    <li><a href="{% url 'fboard:notification' %}">새소식</a>
                        <ul class = "main2">
                            <li><a href="{% url 'fboard:notification' %}">공지사항</a></li>
                            <li><a href="{% url 'fboard:news' %}">뉴스</a></li>
                        </ul>
                    </li>
                    <li><a href="{% url 'comm:community' %}">커뮤니티</a>
                        <ul class = "community">
                            <li><a href="{% url 'comm:community' %}">자유게시판</a></li>
                        </ul>
                    </li>
                    <li><a href="{% url 'event:event' %}">이벤트</a></li>
                </ul>
            </div> 
            <div class="col-lg-3 col-md-4 col-sm-4 text-right fh5co-link-wrap">
                <ul class="fh5co-special" data-offcanvass="yes">
                    <li><a href="{% url 'member:addaccount' %}">회원가입</a></li>
                    <li><a href="{% url 'member:login' %}">로그인</a></li>
                </ul>
            </div>
        </div>
    </nav>
</div>
<div id="fixed_div"></div>
<!--END header-->

midpjt/templates/js.html
{% load static %}
<!-- jQuery -->
<script src="{% static 'js/jquery.min.js' %}"></script>
<!-- jQuery Easing -->
<script src="{% static 'js/jquery.easing.1.3.js' %}"></script>
<!-- Bootstrap -->
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<!-- Waypoints -->
<script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
<!-- Owl Carousel -->
<script src="{% static 'js/owl.carousel.min.js' %}"></script>
<!-- Magnific Popup -->
<script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
<!-- Stellar -->
<script src="{% static 'js/jquery.stellar.min.js' %}"></script>
<!-- countTo -->
<script src="{% static 'js/jquery.countTo.js' %}"></script>
<!-- WOW -->
<script src="{% static 'js/wow.min.js' %}"></script>
<script>
    new WOW().init();
</script>
<!-- Main -->
<script src="{% static 'js/main.js' %}"></script>